services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "9000:9000"
    environment:
      SERVER_PORT: 9000
      USUARIOS_SERVICE_URL: ${USUARIOS_SERVICE_URL}
    networks:
      - ss-net 
    restart: unless-stopped
networks:
  ss-net:
    external: true